services:
  contract-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contract-builder
    command: sh -c "npm run lint && npm run bundle"
    volumes:
      - ./openapi:/app/openapi
      - ./dist:/app/dist

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    depends_on:
      contract-builder:
        condition: service_completed_successfully
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/openapi.yaml
    ports:
      - "8081:8080"
    volumes:
      - ./dist/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    container_name: swagger-editor
    ports:
      - "8080:8080"
    environment:
      URL: /spec/openapi.yaml
    volumes:
      - ./openapi/openapi.yaml:/spec/openapi.yaml:ro

  docs-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docs-server
    depends_on:
      contract-builder:
        condition: service_completed_successfully
    command: sh -c "npx http-server dist -p 8082 -c-1"
    ports:
      - "8082:8082"
    volumes:
      - ./dist:/app/dist:ro
